# Generated by Django 3.0.14 on 2022-07-02 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formvalidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=200)),
                ('m', models.EmailField(max_length=200)),
                ('p', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 16, 31, 8, 464486)),
        ),
    ]
